#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# deploy.sh — Build and deploy the OTA admin web interface to S3
#
# Usage:
#   ./deploy.sh                      # full deploy (preflight → build → sync)
#   ./deploy.sh --config foo.config  # use a different config file
#   ./deploy.sh --skip-preflight     # skip validation (not recommended)
#   ./deploy.sh --build-only         # build locally, do not sync to S3
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail
export AWS_PAGER="" PAGER=cat

DIR="$(cd "$(dirname "$0")" && pwd)"

# ── Parse arguments ───────────────────────────────────────────────────────────
CONFIG_FILE="${DIR}/deploy.config"
SKIP_PREFLIGHT=false
BUILD_ONLY=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --config)          CONFIG_FILE="$2"; shift 2 ;;
    --skip-preflight)  SKIP_PREFLIGHT=true; shift ;;
    --build-only)      BUILD_ONLY=true; shift ;;
    *) echo "Unknown argument: $1"; exit 1 ;;
  esac
done

# ── Load config ───────────────────────────────────────────────────────────────
if [[ ! -f "$CONFIG_FILE" ]]; then
  echo ""
  echo "ERROR: Configuration file not found: $CONFIG_FILE"
  echo ""
  echo "  1. Copy the template:  cp deploy.config.template deploy.config"
  echo "  2. Fill in all values"
  echo "  3. Re-run: ./deploy.sh"
  echo ""
  exit 1
fi
set -a; source "$CONFIG_FILE"; set +a

# ── Preflight ─────────────────────────────────────────────────────────────────
if [[ "$SKIP_PREFLIGHT" == "false" ]]; then
  DEPLOY_CONFIG="$CONFIG_FILE" bash "$DIR/preflight.sh"
  echo ""
fi

# ── Deploy log ────────────────────────────────────────────────────────────────
DEPLOY_LOG="/tmp/ota_admin_ui_deploy_$(date +%Y%m%d_%H%M%S).log"
exec > >(tee -a "$DEPLOY_LOG") 2>&1
echo "$(date '+%H:%M:%S') Deploy log: $DEPLOY_LOG"
echo ""

T_START=$(date +%s)

_ts() { date '+%H:%M:%S'; }
log_ok()   { echo "$(  _ts) [  OK  ] $*"; }
log_info() { echo "$(_ts) [ INFO ] $*"; }
log_step() { echo ""; echo "$(_ts) ── $* ──────────────────────────────────────────"; }

# ── Step 1: Copy logo ─────────────────────────────────────────────────────────
log_step "Logo"

if [[ -n "${LOGO_FILE:-}" && -f "$LOGO_FILE" ]]; then
  EXT="${LOGO_FILE##*.}"
  DEST="$DIR/public/brand-logo.${EXT}"
  cp "$LOGO_FILE" "$DEST"
  log_ok "Copied $LOGO_FILE → public/brand-logo.${EXT}"
  VITE_LOGO_FILENAME="brand-logo.${EXT}"
else
  log_info "LOGO_FILE not set — using existing public/brand-logo.png"
  VITE_LOGO_FILENAME="brand-logo.png"
fi

# ── Step 2: Write .env.production ────────────────────────────────────────────
log_step ".env.production"

cat > "$DIR/.env.production" << ENV
# Auto-generated by deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Do not edit by hand — re-run ./deploy.sh to regenerate.
VITE_API_BASE=${API_BASE}
VITE_COGNITO_URL=${COGNITO_URL}
VITE_COGNITO_CLIENT=${COGNITO_CLIENT}
VITE_BRAND_NAME=${BRAND_NAME:-OTA Admin}
VITE_APP_SUBTITLE=${APP_SUBTITLE:-OTA Admin}
VITE_LOGO_FILENAME=${VITE_LOGO_FILENAME}
ENV

log_ok ".env.production written:"
cat "$DIR/.env.production" | sed 's/^/         /'

# ── Step 3: npm install ───────────────────────────────────────────────────────
log_step "npm install"

cd "$DIR"
npm install --silent
log_ok "Dependencies installed"

# ── Step 4: Build ─────────────────────────────────────────────────────────────
log_step "npm run build"

npm run build
BUILD_SIZE=$(du -sh "$DIR/dist" | cut -f1)
log_ok "Build complete — dist/ size: $BUILD_SIZE"

if [[ "$BUILD_ONLY" == "true" ]]; then
  echo ""
  log_ok "Build-only mode — skipping S3 sync."
  echo "  Output: $DIR/dist/"
  exit 0
fi

# ── Step 5: Sync to S3 ───────────────────────────────────────────────────────
log_step "S3 sync → s3://${S3_BUCKET}/"

# All versioned assets (JS, CSS, images) — long-lived cache
aws s3 sync "$DIR/dist/" "s3://${S3_BUCKET}/" \
  --delete \
  --region "$REGION" \
  --cache-control "public,max-age=31536000,immutable" \
  --exclude "index.html" \
  --exclude "*.map"
log_ok "Assets synced (1-year cache)"

# index.html — must never be cached so users always get the latest version
aws s3 cp "$DIR/dist/index.html" "s3://${S3_BUCKET}/index.html" \
  --region "$REGION" \
  --cache-control "no-cache,no-store,must-revalidate" \
  --content-type "text/html"
log_ok "index.html synced (no-cache)"

# ── Step 6: CloudFront invalidation ──────────────────────────────────────────
if [[ -n "${CLOUDFRONT_DIST_ID:-}" ]]; then
  log_step "CloudFront invalidation"
  INVAL_ID=$(aws cloudfront create-invalidation \
    --distribution-id "$CLOUDFRONT_DIST_ID" \
    --paths "/*" \
    --query 'Invalidation.Id' --output text)
  log_ok "Invalidation submitted: $INVAL_ID"
  log_info "CDN cache will clear within ~60 seconds"
fi

# ── Summary ───────────────────────────────────────────────────────────────────
T_END=$(date +%s)
ELAPSED=$(( T_END - T_START ))
echo ""
echo "════════════════════════════════════════════════════════════════"
log_ok "Admin UI deployed in ${ELAPSED}s"
echo ""
echo "  S3 bucket : s3://${S3_BUCKET}/"
if [[ -n "${CLOUDFRONT_DIST_ID:-}" ]]; then
echo "  CloudFront: https://$(aws cloudfront get-distribution \
    --id "$CLOUDFRONT_DIST_ID" \
    --query 'Distribution.DomainName' --output text 2>/dev/null || echo "$CLOUDFRONT_DIST_ID")"
fi
echo "  Log file  : $DEPLOY_LOG"
echo "════════════════════════════════════════════════════════════════"
